### ISSUE TITLE
Suggestion: Method to make the smoke go higher.

### ISSUE THREAD

**Issue by Sandriell** [mortuusars/SootyChimneys#11]
Would love to see a way to make the smoke go higher/last longer. Whether that is through some in game method, like campfires with haybales, or simply through the config.

**Comment by mortuusars** [comment]
It was added in the 1.1.0 version:
- Chimney that has another chimney underneath will now emit a Signal Smoke (like a hay bale under a campfire)

Seems like I forgot to mention it in the description. Should probably fix this.

**Comment by Sandriell** [comment]
Haha ok, just tried it out.

Only minor suggestion, it would be nice if when they stacked, they connected better. Like with the brick/stone chimney, the bottom one should lose the lip around the top to connect cleanly with the one above. The lower terracotta one should become a full block, etc.

**Comment by mortuusars** [comment]
Yeah, that would be nice. I'll do something like this next time I'll have time to work on a mod.
