### ISSUE TITLE
Fabric 1.20.1 Version ?

### ISSUE THREAD

**Issue by TimmyWithTheBat21** [mortuusars/SootyChimneys#16]
Congrats to your Fabric Release for 1.21.
Just a quick Question could it be possible that there will be a 1.20.1 Version ?
Thx regardless of the outcome of the answer

**Comment by MinecraftGuy926** [comment]
bump!

**Comment by mortuusars** [comment]
Fabric 1.20.1 is available. https://legacy.curseforge.com/minecraft/mc-mods/sooty-chimneys-fabric

**Comment by MinecraftGuy926** [comment]
Oh wow, thanks!
