### ISSUE TITLE
Incompatibility with create ? 

### ISSUE THREAD

**Issue by Lilygabe** [mortuusars/SootyChimneys#9]
It might be because the mod updated to the newest version of create and I am at the one before it (0.5.0.i), but there seems to be an incompatibility at loading time with the mod.

Checking the crash log, it seems like this relates to the movement behaviour when on a contraption?

[Here is my crash log](https://bytebin.lucko.me/9vRa9QAlRp)

**Comment by mortuusars** [comment]
Did you try installing previous version of SootyChimneys? 1.1.1 will probably work only with Create 0.5.1.
